"""SQLAlchemy models for Curate AI database."""

import uuid
from datetime import datetime
from typing import Any

from pgvector.sqlalchemy import Vector
from sqlalchemy import JSON, DateTime, Float, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Base class for all SQLAlchemy models."""

    type_annotation_map = {
        dict[str, Any]: JSON,
    }


class AgentRun(Base):
    """Tracks each pipeline execution run."""

    __tablename__ = "agent_runs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    status: Mapped[str] = mapped_column(
        String(20),
        default="running",
    )  # running, completed, failed
    config_hash: Mapped[str | None] = mapped_column(String(64))  # SHA256 of config
    duration_seconds: Mapped[float | None] = mapped_column(Float)
    metadata_: Mapped[dict[str, Any] | None] = mapped_column("metadata", JSON)
    error_message: Mapped[str | None] = mapped_column(Text)

    # Relationships
    topics: Mapped[list["TopicSeen"]] = relationship(back_populates="run")
    angles: Mapped[list["AngleGenerated"]] = relationship(back_populates="run")
    rejected_items: Mapped[list["RejectedItem"]] = relationship(back_populates="run")
    emails: Mapped[list["EmailSent"]] = relationship(back_populates="run")


class TopicSeen(Base):
    """Normalized topic candidates from source scout."""

    __tablename__ = "topics_seen"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agent_runs.id"),
    )
    title: Mapped[str] = mapped_column(String(500))
    source: Mapped[str] = mapped_column(String(100))  # arXiv, blog, github
    source_type: Mapped[str] = mapped_column(String(50))  # research, blog, release
    url: Mapped[str] = mapped_column(String(2000))
    summary: Mapped[str | None] = mapped_column(Text)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    discovered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    # Scoring fields (filled by relevance filter)
    relevance_score: Mapped[float | None] = mapped_column(Float)
    novelty_score: Mapped[float | None] = mapped_column(Float)
    impact_score: Mapped[float | None] = mapped_column(Float)
    combined_score: Mapped[float | None] = mapped_column(Float)

    # Embedding for semantic search
    embedding: Mapped[list[float] | None] = mapped_column(Vector(768))

    # Relationship
    run: Mapped["AgentRun"] = relationship(back_populates="topics")


class AngleGenerated(Base):
    """Insight angles generated by the insight generator."""

    __tablename__ = "angles_generated"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agent_runs.id"),
    )
    topic_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("topics_seen.id"),
    )
    stance: Mapped[str] = mapped_column(Text)  # The opinionated take
    why_it_matters: Mapped[str] = mapped_column(Text)
    second_order_effects: Mapped[list[str]] = mapped_column(JSON)
    relevant_for: Mapped[list[str]] = mapped_column(JSON)  # Audience segments
    confidence: Mapped[float] = mapped_column(Float)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    # Embedding for redundancy check
    embedding: Mapped[list[float] | None] = mapped_column(Vector(768))

    # Final selection flag
    is_selected: Mapped[bool] = mapped_column(default=False)

    # Relationship
    run: Mapped["AgentRun"] = relationship(back_populates="angles")
    scores: Mapped[list["AngleScore"]] = relationship(back_populates="angle")


class AngleScore(Base):
    """Scoring history for angles (for debugging and replay)."""

    __tablename__ = "angle_scores"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    angle_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("angles_generated.id"),
    )
    score_type: Mapped[str] = mapped_column(String(50))  # novelty, clarity, etc.
    score_value: Mapped[float] = mapped_column(Float)
    scored_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    metadata_: Mapped[dict[str, Any] | None] = mapped_column("metadata", JSON)

    # Relationship
    angle: Mapped["AngleGenerated"] = relationship(back_populates="scores")


class RejectedItem(Base):
    """Items rejected during filtering with reasons."""

    __tablename__ = "rejected_items"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agent_runs.id"),
    )
    item_type: Mapped[str] = mapped_column(String(50))  # topic, angle
    item_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True))
    rejection_reason: Mapped[str] = mapped_column(Text)
    rejection_stage: Mapped[str] = mapped_column(String(50))  # filter, redundancy
    rejected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    metadata_: Mapped[dict[str, Any] | None] = mapped_column("metadata", JSON)

    # Relationship
    run: Mapped["AgentRun"] = relationship(back_populates="rejected_items")


class EmailSent(Base):
    """Log of emails sent."""

    __tablename__ = "emails_sent"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agent_runs.id"),
    )
    sent_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    recipient: Mapped[str] = mapped_column(String(500))
    subject: Mapped[str] = mapped_column(String(500))
    angle_ids: Mapped[list[str]] = mapped_column(JSON)  # UUIDs as strings
    email_hash: Mapped[str | None] = mapped_column(String(64))  # Content hash
    success: Mapped[bool] = mapped_column(default=True)
    error_message: Mapped[str | None] = mapped_column(Text)

    # Relationship
    run: Mapped["AgentRun"] = relationship(back_populates="emails")
